"""baseline_from_production_db

Revision ID: b2c6ccfa452a
Revises:
Create Date: 2025-12-29 21:26:13.760391

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b2c6ccfa452a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_backup_lookup_description")
    op.alter_column(
        "amazon_business_connections",
        "is_sandbox",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="TRUE for sandbox environment, FALSE for production",
        existing_nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "amazon_business_connections",
        "marketplace_id",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Amazon marketplace ID (e.g., A1F83G8C2ARO7P for UK)",
        existing_nullable=True,
        existing_server_default=sa.text("'A1F83G8C2ARO7P'::character varying"),
    )
    op.alter_column(
        "amazon_business_connections",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of last successful order sync",
        existing_nullable=True,
    )
    op.drop_index("idx_ab_orders_order_id", table_name="amazon_business_orders")
    op.drop_constraint(
        "amazon_returns_reversal_id_key", "amazon_returns", type_="unique"
    )
    op.drop_constraint(
        "bank_connections_user_id_provider_id_key", "bank_connections", type_="unique"
    )
    op.drop_constraint(
        "category_keywords_category_name_keyword_key",
        "category_keywords",
        type_="unique",
    )
    op.alter_column(
        "category_rules",
        "pattern_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'contains'::character varying"),
    )
    op.alter_column(
        "category_rules",
        "priority",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "category_rules",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "category_rules",
        "source",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'manual'::character varying"),
    )
    op.alter_column(
        "category_rules",
        "usage_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index("idx_category_rules_category_id", table_name="category_rules")
    op.drop_index("idx_category_rules_pattern", table_name="category_rules")
    op.drop_index("idx_category_rules_priority", table_name="category_rules")
    op.drop_index("idx_category_rules_subcategory_id", table_name="category_rules")
    op.drop_index("idx_category_rules_type", table_name="category_rules")
    op.drop_index("idx_connection_logs_connection_id", table_name="connection_logs")
    op.drop_index("idx_connection_logs_created_at", table_name="connection_logs")
    op.alter_column(
        "custom_categories",
        "user_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "custom_categories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index("idx_custom_categories_type", table_name="custom_categories")
    op.drop_index("idx_custom_categories_user", table_name="custom_categories")
    op.drop_index(
        "idx_gmail_merchant_aliases_bank", table_name="gmail_merchant_aliases"
    )
    op.drop_index(
        "idx_gmail_merchant_aliases_receipt", table_name="gmail_merchant_aliases"
    )
    op.drop_index(
        "idx_merchant_stats_connection", table_name="gmail_merchant_statistics"
    )
    op.drop_index("idx_merchant_stats_merchant", table_name="gmail_merchant_statistics")
    op.drop_index("idx_merchant_stats_method", table_name="gmail_merchant_statistics")
    op.drop_index("idx_merchant_stats_period", table_name="gmail_merchant_statistics")
    op.alter_column(
        "gmail_parse_statistics",
        "match_attempted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_index("idx_errors_connection", table_name="gmail_processing_errors")
    op.drop_index("idx_errors_job", table_name="gmail_processing_errors")
    op.drop_index("idx_errors_occurred", table_name="gmail_processing_errors")
    op.drop_index("idx_errors_stage", table_name="gmail_processing_errors")
    op.drop_index("idx_errors_type", table_name="gmail_processing_errors")
    op.alter_column(
        "gmail_receipts",
        "pdf_processing_status",
        existing_type=sa.VARCHAR(length=20),
        comment="Status of async PDF processing: none, pending, processing, completed, failed, skipped",
        existing_nullable=True,
        existing_server_default=sa.text("'none'::character varying"),
    )
    op.alter_column(
        "gmail_sync_jobs",
        "stats",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment='Aggregated statistics JSON: {\r\n  "by_parse_method": {"vendor_amazon": {"parsed": 45, "failed": 2}},\r\n  "by_merchant": {"amazon.co.uk": {"parsed": 45, "failed": 2}},\r\n  "datapoint_extraction": {\r\n    "merchant": {"attempted": 100, "success": 95},\r\n    "amount": {"attempted": 100, "success": 88}\r\n  },\r\n  "errors": {"api_error": 3, "parse_error": 5}\r\n}',
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_table_comment(
        "matching_jobs",
        existing_comment="Tracks async matching jobs for Amazon, Apple, and Returns matching operations",
        schema=None,
    )
    op.alter_column(
        "merchant_normalizations",
        "pattern_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'contains'::character varying"),
    )
    op.alter_column(
        "merchant_normalizations",
        "priority",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "merchant_normalizations",
        "source",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'manual'::character varying"),
    )
    op.alter_column(
        "merchant_normalizations",
        "usage_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index("idx_merchant_norm_pattern", table_name="merchant_normalizations")
    op.drop_index("idx_merchant_norm_priority", table_name="merchant_normalizations")
    op.alter_column(
        "normalized_categories",
        "is_system",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "normalized_categories",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "normalized_categories",
        "is_essential",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "normalized_categories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index(
        "idx_normalized_categories_active", table_name="normalized_categories"
    )
    op.drop_index("idx_normalized_categories_name", table_name="normalized_categories")
    op.drop_index(
        "idx_normalized_categories_system", table_name="normalized_categories"
    )
    op.alter_column(
        "normalized_subcategories",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "normalized_subcategories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index(
        "idx_normalized_subcategories_category", table_name="normalized_subcategories"
    )
    op.drop_index(
        "idx_normalized_subcategories_name", table_name="normalized_subcategories"
    )
    op.drop_index("idx_oauth_state_state", table_name="oauth_state")
    op.create_index("idx_oauth_state_state", "oauth_state", ["state"], unique=True)
    op.alter_column(
        "security_audit_log",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="JSONB field for flexible audit data (attempted_username, blocked_reason, etc.)",
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index("idx_security_audit_event_type", table_name="security_audit_log")
    op.drop_index("idx_security_audit_ip", table_name="security_audit_log")
    op.drop_index("idx_security_audit_timestamp", table_name="security_audit_log")
    op.drop_index("idx_security_audit_user_id", table_name="security_audit_log")
    op.drop_table_comment(
        "security_audit_log",
        existing_comment="Audit trail for security events (login attempts, rate limiting, etc.)",
        schema=None,
    )
    op.drop_index(
        "idx_subcategory_mappings_category", table_name="subcategory_mappings"
    )
    op.drop_index(
        "idx_subcategory_mappings_subcategory", table_name="subcategory_mappings"
    )
    op.drop_constraint(
        "truelayer_accounts_connection_id_account_id_key",
        "truelayer_accounts",
        type_="unique",
    )
    op.create_index(
        "idx_ab_matches_transaction",
        "truelayer_amazon_business_matches",
        ["truelayer_transaction_id"],
        unique=False,
    )
    op.drop_index(
        "idx_truelayer_card_transactions_timestamp",
        table_name="truelayer_card_transactions",
    )
    op.drop_constraint(
        "truelayer_card_transactions_normalised_provider_id_key",
        "truelayer_card_transactions",
        type_="unique",
    )
    op.drop_constraint(
        "truelayer_cards_connection_id_card_id_key", "truelayer_cards", type_="unique"
    )
    op.create_index(
        op.f("ix_truelayer_cards_connection_id"),
        "truelayer_cards",
        ["connection_id", "card_id"],
        unique=True,
    )
    op.drop_index(
        "idx_enrichment_jobs_created_at", table_name="truelayer_enrichment_jobs"
    )
    op.create_index(
        "idx_enrichment_jobs_created_at",
        "truelayer_enrichment_jobs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index("idx_import_jobs_created_at", table_name="truelayer_import_jobs")
    op.create_index(
        "idx_import_jobs_created_at",
        "truelayer_import_jobs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.alter_column(
        "user_sessions",
        "session_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default="{}",
        existing_nullable=False,
    )
    op.drop_index("idx_user_sessions_expires_at", table_name="user_sessions")
    op.drop_index("idx_user_sessions_user_id", table_name="user_sessions")
    op.create_table_comment(
        "user_sessions",
        "User sessions for authentication",
        existing_comment="User session tracking (alternative to Redis-only sessions)",
        schema=None,
    )
    op.drop_index("idx_webhook_events_event_id", table_name="webhook_events")
    op.create_index(
        "idx_webhook_events_event_id", "webhook_events", ["event_id"], unique=True
    )
    op.drop_table_comment(
        "webhook_events",
        existing_comment="TrueLayer webhook events for asynchronous processing",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "webhook_events",
        "TrueLayer webhook events for asynchronous processing",
        existing_comment=None,
        schema=None,
    )
    op.drop_index("idx_webhook_events_event_id", table_name="webhook_events")
    op.create_index(
        "idx_webhook_events_event_id", "webhook_events", ["event_id"], unique=False
    )
    op.create_table_comment(
        "user_sessions",
        "User session tracking (alternative to Redis-only sessions)",
        existing_comment="User sessions for authentication",
        schema=None,
    )
    op.create_index(
        "idx_user_sessions_user_id", "user_sessions", ["user_id"], unique=False
    )
    op.create_index(
        "idx_user_sessions_expires_at", "user_sessions", ["expires_at"], unique=False
    )
    op.alter_column(
        "user_sessions",
        "session_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(
        "idx_import_jobs_created_at",
        table_name="truelayer_import_jobs",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_import_jobs_created_at",
        "truelayer_import_jobs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_enrichment_jobs_created_at",
        table_name="truelayer_enrichment_jobs",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_enrichment_jobs_created_at",
        "truelayer_enrichment_jobs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(
        op.f("ix_truelayer_cards_connection_id"), table_name="truelayer_cards"
    )
    op.create_unique_constraint(
        "truelayer_cards_connection_id_card_id_key",
        "truelayer_cards",
        ["connection_id", "card_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        "truelayer_card_transactions_normalised_provider_id_key",
        "truelayer_card_transactions",
        ["normalised_provider_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        "idx_truelayer_card_transactions_timestamp",
        "truelayer_card_transactions",
        ["timestamp"],
        unique=False,
    )
    op.drop_index(
        "idx_ab_matches_transaction", table_name="truelayer_amazon_business_matches"
    )
    op.create_unique_constraint(
        "truelayer_accounts_connection_id_account_id_key",
        "truelayer_accounts",
        ["connection_id", "account_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        "idx_subcategory_mappings_subcategory",
        "subcategory_mappings",
        ["subcategory_name"],
        unique=False,
    )
    op.create_index(
        "idx_subcategory_mappings_category",
        "subcategory_mappings",
        ["custom_category_id"],
        unique=False,
    )
    op.create_table_comment(
        "security_audit_log",
        "Audit trail for security events (login attempts, rate limiting, etc.)",
        existing_comment=None,
        schema=None,
    )
    op.create_index(
        "idx_security_audit_user_id", "security_audit_log", ["user_id"], unique=False
    )
    op.create_index(
        "idx_security_audit_timestamp",
        "security_audit_log",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "idx_security_audit_ip", "security_audit_log", ["ip_address"], unique=False
    )
    op.create_index(
        "idx_security_audit_event_type",
        "security_audit_log",
        ["event_type"],
        unique=False,
    )
    op.alter_column(
        "security_audit_log",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="JSONB field for flexible audit data (attempted_username, blocked_reason, etc.)",
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index("idx_oauth_state_state", table_name="oauth_state")
    op.create_index("idx_oauth_state_state", "oauth_state", ["state"], unique=False)
    op.create_index(
        "idx_normalized_subcategories_name",
        "normalized_subcategories",
        ["name"],
        unique=False,
    )
    op.create_index(
        "idx_normalized_subcategories_category",
        "normalized_subcategories",
        ["category_id"],
        unique=False,
    )
    op.alter_column(
        "normalized_subcategories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "normalized_subcategories",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_index(
        "idx_normalized_categories_system",
        "normalized_categories",
        ["is_system"],
        unique=False,
    )
    op.create_index(
        "idx_normalized_categories_name",
        "normalized_categories",
        ["name"],
        unique=False,
    )
    op.create_index(
        "idx_normalized_categories_active",
        "normalized_categories",
        ["is_active"],
        unique=False,
    )
    op.alter_column(
        "normalized_categories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "normalized_categories",
        "is_essential",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "normalized_categories",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "normalized_categories",
        "is_system",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.create_index(
        "idx_merchant_norm_priority",
        "merchant_normalizations",
        [sa.literal_column("priority DESC")],
        unique=False,
    )
    op.create_index(
        "idx_merchant_norm_pattern",
        "merchant_normalizations",
        ["pattern"],
        unique=False,
    )
    op.alter_column(
        "merchant_normalizations",
        "usage_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "merchant_normalizations",
        "source",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'manual'::character varying"),
    )
    op.alter_column(
        "merchant_normalizations",
        "priority",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "merchant_normalizations",
        "pattern_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'contains'::character varying"),
    )
    op.create_table_comment(
        "matching_jobs",
        "Tracks async matching jobs for Amazon, Apple, and Returns matching operations",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "gmail_sync_jobs",
        "stats",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment='Aggregated statistics JSON: {\r\n  "by_parse_method": {"vendor_amazon": {"parsed": 45, "failed": 2}},\r\n  "by_merchant": {"amazon.co.uk": {"parsed": 45, "failed": 2}},\r\n  "datapoint_extraction": {\r\n    "merchant": {"attempted": 100, "success": 95},\r\n    "amount": {"attempted": 100, "success": 88}\r\n  },\r\n  "errors": {"api_error": 3, "parse_error": 5}\r\n}',
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "gmail_receipts",
        "pdf_processing_status",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Status of async PDF processing: none, pending, processing, completed, failed, skipped",
        existing_nullable=True,
        existing_server_default=sa.text("'none'::character varying"),
    )
    op.create_index(
        "idx_errors_type", "gmail_processing_errors", ["error_type"], unique=False
    )
    op.create_index(
        "idx_errors_stage", "gmail_processing_errors", ["error_stage"], unique=False
    )
    op.create_index(
        "idx_errors_occurred", "gmail_processing_errors", ["occurred_at"], unique=False
    )
    op.create_index(
        "idx_errors_job", "gmail_processing_errors", ["sync_job_id"], unique=False
    )
    op.create_index(
        "idx_errors_connection",
        "gmail_processing_errors",
        ["connection_id"],
        unique=False,
    )
    op.alter_column(
        "gmail_parse_statistics",
        "match_attempted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.create_index(
        "idx_merchant_stats_period",
        "gmail_merchant_statistics",
        ["period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        "idx_merchant_stats_method",
        "gmail_merchant_statistics",
        ["parse_method"],
        unique=False,
    )
    op.create_index(
        "idx_merchant_stats_merchant",
        "gmail_merchant_statistics",
        ["merchant_normalized"],
        unique=False,
    )
    op.create_index(
        "idx_merchant_stats_connection",
        "gmail_merchant_statistics",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        "idx_gmail_merchant_aliases_receipt",
        "gmail_merchant_aliases",
        [sa.literal_column("lower(receipt_name::text)")],
        unique=False,
    )
    op.create_index(
        "idx_gmail_merchant_aliases_bank",
        "gmail_merchant_aliases",
        [sa.literal_column("lower(bank_name::text)")],
        unique=False,
    )
    op.create_index(
        "idx_custom_categories_user", "custom_categories", ["user_id"], unique=False
    )
    op.create_index(
        "idx_custom_categories_type",
        "custom_categories",
        ["category_type"],
        unique=False,
    )
    op.alter_column(
        "custom_categories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "custom_categories",
        "user_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.create_index(
        "idx_connection_logs_created_at",
        "connection_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_connection_logs_connection_id",
        "connection_logs",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        "idx_category_rules_type", "category_rules", ["transaction_type"], unique=False
    )
    op.create_index(
        "idx_category_rules_subcategory_id",
        "category_rules",
        ["subcategory_id"],
        unique=False,
    )
    op.create_index(
        "idx_category_rules_priority",
        "category_rules",
        [sa.literal_column("priority DESC")],
        unique=False,
    )
    op.create_index(
        "idx_category_rules_pattern",
        "category_rules",
        ["description_pattern"],
        unique=False,
    )
    op.create_index(
        "idx_category_rules_category_id",
        "category_rules",
        ["category_id"],
        unique=False,
    )
    op.alter_column(
        "category_rules",
        "usage_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "category_rules",
        "source",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'manual'::character varying"),
    )
    op.alter_column(
        "category_rules",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "category_rules",
        "priority",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "category_rules",
        "pattern_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'contains'::character varying"),
    )
    op.create_unique_constraint(
        "category_keywords_category_name_keyword_key",
        "category_keywords",
        ["category_name", "keyword"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        "bank_connections_user_id_provider_id_key",
        "bank_connections",
        ["user_id", "provider_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        "amazon_returns_reversal_id_key",
        "amazon_returns",
        ["reversal_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        "idx_ab_orders_order_id", "amazon_business_orders", ["order_id"], unique=False
    )
    op.alter_column(
        "amazon_business_connections",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of last successful order sync",
        existing_nullable=True,
    )
    op.alter_column(
        "amazon_business_connections",
        "marketplace_id",
        existing_type=sa.VARCHAR(length=20),
        comment="Amazon marketplace ID (e.g., A1F83G8C2ARO7P for UK)",
        existing_nullable=True,
        existing_server_default=sa.text("'A1F83G8C2ARO7P'::character varying"),
    )
    op.alter_column(
        "amazon_business_connections",
        "is_sandbox",
        existing_type=sa.BOOLEAN(),
        comment="TRUE for sandbox environment, FALSE for production",
        existing_nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_table(
        "_backup_lookup_description",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("lookup_description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
