"""
Database Layer - Public API

This module provides the public interface for all database operations.
It imports and re-exports functions from domain-specific modules.

Usage:
    from database import get_db, save_gmail_receipt, get_truelayer_accounts
    # or
    import database

Organization:
    - base.py: Connection pool and utilities
    - gmail.py: Gmail receipt operations
    - truelayer.py: TrueLayer bank sync operations
    - amazon.py: Amazon order operations
    - apple.py: Apple transaction operations
    - categories.py: Category and rule operations
    - transactions.py: Transaction CRUD operations
    - matching.py: Cross-source matching operations
    - statistics.py: Analytics queries
    - webhooks.py: Webhook handling
    - import_jobs.py: Import job tracking
    - direct_debit.py: Direct debit mappings
    - merchant_normalization.py: Merchant name normalization
"""

# Core connection utilities (always available)
# (No legacy imports needed - all functions imported from domain modules)

# Amazon operations
from .amazon import (
    check_amazon_coverage,
    clear_amazon_business_data,
    clear_amazon_returns,
    delete_amazon_business_connection,
    get_amazon_business_connection,
    get_amazon_business_order_by_id,
    get_amazon_business_orders,
    get_amazon_business_statistics,
    get_amazon_order_by_id,
    get_amazon_orders,
    get_amazon_returns,
    get_amazon_statistics,
    get_returns_statistics,
    get_truelayer_transaction_for_matching,
    get_unmatched_truelayer_amazon_business_transactions,
    get_unmatched_truelayer_amazon_transactions,
    get_unmatched_truelayer_apple_transactions,
    import_amazon_business_line_items,
    import_amazon_business_orders,
    # Order management
    import_amazon_orders,
    # Returns management
    import_amazon_returns,
    insert_amazon_business_line_item,
    insert_amazon_business_order,
    link_return_to_transactions,
    match_truelayer_amazon_business_transaction,
    match_truelayer_amazon_transaction,
    match_truelayer_apple_transaction,
    # Business account
    save_amazon_business_connection,
    update_amazon_business_product_summaries,
    update_amazon_business_tokens,
)

# Apple transactions operations
from .apple import (
    clear_apple_transactions,
    get_apple_order_ids,
    get_apple_statistics,
    get_apple_transaction_by_id,
    get_apple_transactions,
    import_apple_transactions,
    match_apple_transaction,
)

# SQLAlchemy-based functions (new)
from .base import Base, SessionLocal, engine, get_session

# Categories & Rules operations
from .categories import (
    apply_all_rules_to_transactions,
    create_normalized_category,
    create_normalized_subcategory,
    create_promoted_category,
    delete_normalized_category,
    delete_normalized_subcategory,
    get_category_spending_summary,
    # Category promotion
    get_custom_categories,
    get_essential_category_names,
    get_mapped_subcategories,
    # Normalized categories
    get_normalized_categories,
    get_normalized_category_by_id,
    get_normalized_category_by_name,
    get_normalized_subcategories,
    get_normalized_subcategory_by_id,
    get_rules_statistics,
    get_subcategory_spending,
    hide_category,
    test_all_rules,
    # Rules testing
    test_rule_pattern,
    unhide_category,
    update_normalized_category,
    update_normalized_subcategory,
)

# Direct debit mapping operations
from .direct_debit import (
    apply_direct_debit_mappings,
    delete_direct_debit_mapping,
    detect_new_direct_debits,
    get_direct_debit_mappings,
    get_direct_debit_payees,
    save_direct_debit_mapping,
)

# Enrichment operations
from .enrichment import (
    # Multi-source enrichment
    add_enrichment_source,
    backfill_pre_enrichment_status,
    clear_amazon_orders,
    clear_enrichment_required_after_success,
    delete_enrichment_source,
    get_all_enrichment_sources_for_transactions,
    get_batch_llm_enrichment_context,
    get_enrichment_source_full_details,
    get_identified_summary,
    get_llm_enrichment_context,
    get_primary_enrichment_description,
    get_required_unenriched_transactions,
    get_transaction_enrichment_sources,
    set_enrichment_required,
    set_primary_enrichment_source,
    # Enrichment status
    toggle_enrichment_required,
    # Pre-enrichment status tracking
    update_pre_enrichment_status,
)

# Domain-specific modules
# Gmail operations
from .gmail import (
    cleanup_expired_gmail_oauth_states,
    cleanup_stale_gmail_jobs,
    # Sync jobs
    complete_gmail_sync_job,
    confirm_gmail_match,
    create_gmail_sync_job,
    delete_gmail_connection,
    delete_gmail_match,
    delete_old_unmatched_gmail_receipts,
    get_amazon_order_for_transaction,
    get_apple_transaction_for_match,
    get_gmail_connection,
    get_gmail_connection_by_id,
    get_gmail_email_content,
    get_gmail_error_summary,
    get_gmail_matches,
    get_gmail_matches_for_transaction,
    get_gmail_merchant_alias,
    get_gmail_merchant_statistics,
    # Merchant aggregation
    get_gmail_merchants_summary,
    get_gmail_oauth_state,
    get_gmail_receipt_by_id,
    get_gmail_receipt_by_message_id,
    get_gmail_receipts,
    get_gmail_sender_pattern,
    get_gmail_sender_patterns_list,
    # Statistics
    get_gmail_statistics,
    get_gmail_sync_job,
    get_latest_active_gmail_sync_job,
    get_latest_gmail_sync_job,
    get_llm_queue_summary,
    get_source_coverage_dates,
    get_transactions_for_matching,
    get_unmatched_gmail_receipts,
    # LLM queue
    get_unparseable_receipts_for_llm_queue,
    get_user_by_email,
    get_user_by_id,
    get_user_by_username,
    # User management
    insert_user,
    log_security_event,
    # Connection management
    save_gmail_connection,
    # Email content
    save_gmail_email_content,
    save_gmail_email_content_bulk,
    # Error tracking
    save_gmail_error,
    # Matching
    save_gmail_match,
    save_gmail_parse_statistic,
    # Receipt operations
    save_gmail_receipt,
    save_gmail_receipt_bulk,
    soft_delete_gmail_receipt,
    # OAuth state
    store_gmail_oauth_state,
    update_gmail_connection_status,
    update_gmail_history_id,
    update_gmail_receipt_from_pdf,
    # Receipt updates
    update_gmail_receipt_parsed,
    update_gmail_receipt_pdf_status,
    update_gmail_receipt_status,
    update_gmail_sync_job_dates,
    update_gmail_sync_job_progress,
    update_gmail_sync_job_stats,
    update_gmail_tokens,
    update_receipt_llm_status,
    update_user_last_login,
    update_user_password,
    update_user_username,
)
from .matching import (
    add_category_rule,
    add_merchant_normalization,
    cleanup_stale_matching_jobs,
    # Matching job tracking
    create_matching_job,
    delete_category_rule,
    delete_merchant_normalization,
    get_active_matching_jobs,
    get_category_rules,
    get_matching_job,
    get_merchant_normalizations,
    increment_merchant_normalization_usage,
    increment_rule_usage,
    update_category_rule,
    update_matching_job_progress,
    update_matching_job_status,
    update_merchant_normalization,
)

# PDF attachment operations
from .pdf import (
    delete_pdf_attachment,
    get_pdf_attachment_by_hash,
    get_pdf_attachment_by_id,
    get_pdf_attachments_for_receipt,
    get_pdf_storage_stats,
    save_pdf_attachment,
)

# Core transaction operations
from .transactions import (
    add_account_mapping,
    add_category_keyword,
    cache_enrichment,
    create_custom_category,
    delete_account_mapping,
    delete_custom_category,
    get_account_mapping_by_details,
    # Account mappings
    get_all_account_mappings,
    # Category keywords (legacy)
    get_all_categories,
    get_all_transactions,
    get_category_keywords,
    get_enrichment_from_cache,
    get_huququllah_summary,
    get_transaction_by_id,
    get_unclassified_transactions,
    is_transaction_enriched,
    log_enrichment_failure,
    remove_category_keyword,
    update_account_mapping,
    update_transaction_huququllah,
    # Transaction enrichment utilities
    update_transaction_with_enrichment,
    # Transaction operations
    update_truelayer_transaction_merchant,
)

# TrueLayer operations
from .truelayer import (
    add_import_progress,
    count_enriched_truelayer_transactions,
    # Enrichment
    create_enrichment_job,
    # Import job management
    create_import_job,
    delete_oauth_state,
    get_account_by_truelayer_id,
    get_all_truelayer_card_transactions,
    get_all_truelayer_transactions,
    get_all_truelayer_transactions_with_enrichment,
    get_card_by_truelayer_id,
    get_card_transaction_by_id,
    get_connection,
    get_connection_accounts,
    get_connection_cards,
    get_import_job,
    get_import_progress,
    get_job_transaction_ids,
    get_latest_balance_snapshots,
    get_latest_card_balance_snapshots,
    get_oauth_state,
    get_transaction_enrichment,
    # Transaction operations
    get_truelayer_transaction_by_id,
    get_truelayer_transaction_by_pk,
    get_unenriched_truelayer_transactions,
    # Connection management
    get_user_connections,
    get_user_import_history,
    get_webhook_events,
    # Balance snapshots
    insert_balance_snapshot,
    insert_card_balance_snapshot,
    insert_truelayer_card_transaction,
    insert_truelayer_transaction,
    # Webhook operations
    insert_webhook_event,
    mark_job_completed,
    mark_webhook_processed,
    save_bank_connection,
    save_connection_account,
    # Card operations
    save_connection_card,
    # OAuth state
    store_oauth_state,
    update_account_last_synced,
    update_card_last_synced,
    update_connection_last_synced,
    update_connection_provider,
    update_connection_provider_name,
    update_connection_status,
    update_connection_tokens,
    update_enrichment_job,
    update_import_job_status,
)

# Public API
__all__ = [
    # Core utilities (SQLAlchemy)
    "Base",
    "engine",
    "SessionLocal",
    "get_session",
    # Gmail operations
    "save_gmail_connection",
    "get_gmail_connection",
    "get_gmail_connection_by_id",
    "update_gmail_tokens",
    "update_gmail_connection_status",
    "update_gmail_history_id",
    "delete_gmail_connection",
    "store_gmail_oauth_state",
    "get_gmail_oauth_state",
    "delete_gmail_oauth_state",
    "cleanup_expired_gmail_oauth_states",
    "save_gmail_receipt",
    "save_gmail_receipt_bulk",
    "get_gmail_receipts",
    "get_gmail_receipt_by_id",
    "get_gmail_receipt_by_message_id",
    "get_unmatched_gmail_receipts",
    "soft_delete_gmail_receipt",
    "get_pending_gmail_receipts",
    "delete_old_unmatched_gmail_receipts",
    "save_gmail_email_content",
    "save_gmail_email_content_bulk",
    "get_gmail_email_content",
    "get_receipt_with_email_content",
    "get_receipts_by_domain_with_content",
    "update_gmail_receipt_parsed",
    "update_gmail_receipt_status",
    "update_gmail_receipt_pdf_status",
    "update_gmail_receipt_from_pdf",
    "save_gmail_match",
    "get_gmail_matches_for_transaction",
    "get_amazon_order_for_transaction",
    "get_apple_transaction_for_match",
    "get_gmail_matches",
    "confirm_gmail_match",
    "delete_gmail_match",
    "create_gmail_sync_job",
    "update_gmail_sync_job_progress",
    "update_gmail_sync_job_dates",
    "complete_gmail_sync_job",
    "cleanup_stale_gmail_jobs",
    "get_gmail_sync_job",
    "get_latest_gmail_sync_job",
    "get_latest_active_gmail_sync_job",
    "get_gmail_statistics",
    "get_source_coverage_dates",
    "get_gmail_sender_pattern",
    "get_gmail_merchants_summary",
    "get_receipts_by_domain",
    "get_gmail_sender_patterns_list",
    "get_transactions_for_matching",
    "get_gmail_merchant_alias",
    "get_unparseable_receipts_for_llm_queue",
    "get_llm_queue_summary",
    "update_receipt_llm_status",
    "get_receipt_for_llm_processing",
    "save_pdf_attachment",
    "get_pdf_attachment_by_hash",
    "get_pdf_attachments_for_receipt",
    "get_pdf_attachment_by_id",
    "get_pdf_storage_stats",
    "delete_pdf_attachment",
    "save_gmail_error",
    "save_gmail_parse_statistic",
    "update_gmail_sync_job_stats",
    "get_gmail_error_summary",
    "get_gmail_merchant_statistics",
    "create_matching_job",
    "update_matching_job_status",
    "update_matching_job_progress",
    "get_matching_job",
    "get_active_matching_jobs",
    "cleanup_stale_matching_jobs",
    "insert_user",
    "get_user_by_id",
    "get_user_by_username",
    "get_user_by_email",
    "update_user_last_login",
    "update_user_password",
    "update_user_username",
    "log_security_event",
    # TrueLayer operations
    "get_user_connections",
    "get_connection",
    "get_connection_accounts",
    "get_account_by_truelayer_id",
    "save_bank_connection",
    "update_connection_status",
    "update_connection_provider_name",
    "update_connection_provider",
    "update_connection_last_synced",
    "update_connection_tokens",
    "update_account_last_synced",
    "save_connection_account",
    "get_truelayer_transaction_by_id",
    "get_truelayer_transaction_by_pk",
    "insert_truelayer_transaction",
    "get_all_truelayer_transactions",
    "get_all_truelayer_transactions_with_enrichment",
    "insert_webhook_event",
    "mark_webhook_processed",
    "get_webhook_events",
    "insert_balance_snapshot",
    "get_latest_balance_snapshots",
    "save_connection_card",
    "get_connection_cards",
    "get_card_by_truelayer_id",
    "update_card_last_synced",
    "get_card_transaction_by_id",
    "insert_truelayer_card_transaction",
    "get_all_truelayer_card_transactions",
    "insert_card_balance_snapshot",
    "get_latest_card_balance_snapshots",
    "store_oauth_state",
    "get_oauth_state",
    "delete_oauth_state",
    "create_import_job",
    "get_import_job",
    "update_import_job_status",
    "add_import_progress",
    "get_import_progress",
    "mark_job_completed",
    "get_user_import_history",
    "get_job_transaction_ids",
    "create_enrichment_job",
    "update_enrichment_job",
    "get_unenriched_truelayer_transactions",
    "get_transaction_enrichment",
    "count_enriched_truelayer_transactions",
    # Categories & Rules operations
    "get_custom_categories",
    "get_category_spending_summary",
    "get_subcategory_spending",
    "create_promoted_category",
    "hide_category",
    "unhide_category",
    "get_mapped_subcategories",
    "test_rule_pattern",
    "get_rules_statistics",
    "test_all_rules",
    "apply_all_rules_to_transactions",
    "get_normalized_categories",
    "get_normalized_category_by_id",
    "get_normalized_category_by_name",
    "create_normalized_category",
    "update_normalized_category",
    "delete_normalized_category",
    "get_normalized_subcategories",
    "get_normalized_subcategory_by_id",
    "create_normalized_subcategory",
    "update_normalized_subcategory",
    "delete_normalized_subcategory",
    "get_essential_category_names",
    # Apple transactions operations
    "import_apple_transactions",
    "get_apple_order_ids",
    "get_apple_transactions",
    "get_apple_transaction_by_id",
    "get_apple_statistics",
    "clear_apple_transactions",
    "match_apple_transaction",
    # Direct debit mapping operations
    "get_direct_debit_payees",
    "get_direct_debit_mappings",
    "save_direct_debit_mapping",
    "delete_direct_debit_mapping",
    "apply_direct_debit_mappings",
    "detect_new_direct_debits",
    # PDF attachment operations
    "save_pdf_attachment",
    "get_pdf_attachment_by_hash",
    "get_pdf_attachments_for_receipt",
    "get_pdf_attachment_by_id",
    "get_pdf_storage_stats",
    "delete_pdf_attachment",
    # Amazon operations
    "import_amazon_orders",
    "get_amazon_orders",
    "get_amazon_order_by_id",
    "get_unmatched_truelayer_amazon_transactions",
    "get_truelayer_transaction_for_matching",
    "match_truelayer_amazon_transaction",
    "get_unmatched_truelayer_apple_transactions",
    "match_truelayer_apple_transaction",
    "check_amazon_coverage",
    "get_amazon_statistics",
    "import_amazon_returns",
    "get_amazon_returns",
    "link_return_to_transactions",
    "get_returns_statistics",
    "clear_amazon_returns",
    "save_amazon_business_connection",
    "get_amazon_business_connection",
    "update_amazon_business_tokens",
    "import_amazon_business_orders",
    "import_amazon_business_line_items",
    "get_amazon_business_orders",
    "get_amazon_business_statistics",
    "get_unmatched_truelayer_amazon_business_transactions",
    "match_truelayer_amazon_business_transaction",
    "delete_amazon_business_connection",
    "clear_amazon_business_data",
    "get_amazon_business_order_by_id",
    "insert_amazon_business_order",
    "insert_amazon_business_line_item",
    "update_amazon_business_product_summaries",
    # Enrichment operations
    "add_enrichment_source",
    "get_transaction_enrichment_sources",
    "get_all_enrichment_sources_for_transactions",
    "set_primary_enrichment_source",
    "get_primary_enrichment_description",
    "get_llm_enrichment_context",
    "get_batch_llm_enrichment_context",
    "delete_enrichment_source",
    "get_enrichment_source_full_details",
    "clear_amazon_orders",
    "toggle_enrichment_required",
    "set_enrichment_required",
    "get_required_unenriched_transactions",
    "clear_enrichment_required_after_success",
    "update_pre_enrichment_status",
    "get_identified_summary",
    "backfill_pre_enrichment_status",
    # Matching & consistency operations
    "get_category_rules",
    "get_merchant_normalizations",
    "increment_rule_usage",
    "increment_merchant_normalization_usage",
    "add_category_rule",
    "add_merchant_normalization",
    "delete_category_rule",
    "delete_merchant_normalization",
    "update_category_rule",
    "update_merchant_normalization",
    # Core transaction operations
    "get_all_categories",
    "get_category_keywords",
    "add_category_keyword",
    "remove_category_keyword",
    "create_custom_category",
    "delete_custom_category",
    "update_transaction_with_enrichment",
    "is_transaction_enriched",
    "get_enrichment_from_cache",
    "cache_enrichment",
    "log_enrichment_failure",
    "get_all_account_mappings",
    "add_account_mapping",
    "update_account_mapping",
    "delete_account_mapping",
    "get_account_mapping_by_details",
    "update_truelayer_transaction_merchant",
    "update_transaction_huququllah",
    "get_unclassified_transactions",
    "get_huququllah_summary",
    "get_transaction_by_id",
    "get_all_transactions",
]
