# list of languages for which language servers are started; choose from:
#   al               bash             clojure          cpp              csharp           csharp_omnisharp
#   dart             elixir           elm              erlang           fortran          go
#   haskell          java             julia            kotlin           lua              markdown
#   nix              perl             php              python           python_jedi      r
#   rego             ruby             ruby_solargraph  rust             scala            swift
#   terraform        typescript       typescript_vts   yaml             zig
# Note:
#   - For C, use cpp
#   - For JavaScript, use typescript
# Special requirements:
#   - csharp: Requires the presence of a .sln file in the project folder.
# When using multiple languages, the first language server that supports a given file will be used for that file.
# The first language is the default language and the respective language server will be used as a fallback.
# Note that when using the JetBrains backend, language servers are not used and this list is correspondingly ignored.
languages:
- python

# the encoding used by text files in the project
# For a list of possible encodings, see https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: "utf-8"

# whether to use the project's gitignore file to ignore files
# Added on 2025-04-07
ignore_all_files_in_gitignore: true

# list of additional paths to ignore
# same syntax as gitignore, so you can use * and **
# Was previously called `ignored_dirs`, please update your config if you are using that.
# Added (renamed) on 2025-04-07
ignored_paths:
  - "venv/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - ".pytest_cache/**"
  - "migrations/__pycache__/**"
  - ".ruff_cache/**"
  - "*.egg-info/**"

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# list of tool names to exclude. We recommend not excluding any tools, see the readme for more details.
# Below is the complete list of tools for convenience.
# To make sure you have the latest list of tools, and to view their descriptions,
# execute `uv run scripts/print_tool_overview.py`.
#
#  * `activate_project`: Activates a project by name.
#  * `check_onboarding_performed`: Checks whether project onboarding was already performed.
#  * `create_text_file`: Creates/overwrites a file in the project directory.
#  * `delete_lines`: Deletes a range of lines within a file.
#  * `delete_memory`: Deletes a memory from Serena's project-specific memory store.
#  * `execute_shell_command`: Executes a shell command.
#  * `find_referencing_code_snippets`: Finds code snippets in which the symbol at the given location is referenced.
#  * `find_referencing_symbols`: Finds symbols that reference the symbol at the given location (optionally filtered by type).
#  * `find_symbol`: Performs a global (or local) search for symbols with/containing a given name/substring (optionally filtered by type).
#  * `get_current_config`: Prints the current configuration of the agent, including the active and available projects, tools, contexts, and modes.
#  * `get_symbols_overview`: Gets an overview of the top-level symbols defined in a given file.
#  * `initial_instructions`: Gets the initial instructions for the current project.
#     Should only be used in settings where the system prompt cannot be set,
#     e.g. in clients you have no control over, like Claude Desktop.
#  * `insert_after_symbol`: Inserts content after the end of the definition of a given symbol.
#  * `insert_at_line`: Inserts content at a given line in a file.
#  * `insert_before_symbol`: Inserts content before the beginning of the definition of a given symbol.
#  * `list_dir`: Lists files and directories in the given directory (optionally with recursion).
#  * `list_memories`: Lists memories in Serena's project-specific memory store.
#  * `onboarding`: Performs onboarding (identifying the project structure and essential tasks, e.g. for testing or building).
#  * `prepare_for_new_conversation`: Provides instructions for preparing for a new conversation (in order to continue with the necessary context).
#  * `read_file`: Reads a file within the project directory.
#  * `read_memory`: Reads the memory with the given name from Serena's project-specific memory store.
#  * `remove_project`: Removes a project from the Serena configuration.
#  * `replace_lines`: Replaces a range of lines within a file with new content.
#  * `replace_symbol_body`: Replaces the full definition of a symbol.
#  * `restart_language_server`: Restarts the language server, may be necessary when edits not through Serena happen.
#  * `search_for_pattern`: Performs a search for a pattern in the project.
#  * `summarize_changes`: Provides instructions for summarizing the changes made to the codebase.
#  * `switch_modes`: Activates modes by providing a list of their names
#  * `think_about_collected_information`: Thinking tool for pondering the completeness of collected information.
#  * `think_about_task_adherence`: Thinking tool for determining whether the agent is still on track with the current task.
#  * `think_about_whether_you_are_done`: Thinking tool for determining whether the task is truly completed.
#  * `write_memory`: Writes a named memory (for future reference) to Serena's project-specific memory store.
excluded_tools: []

# initial prompt for the project. It will always be given to the LLM upon activating the project
# (contrary to the memories, which are loaded on demand).
initial_prompt: |
  # Personal Spending App - Backend (Python/Flask)

  ## Project Context
  This is a Flask backend for a personal spending analysis application that integrates with:
  - TrueLayer API (UK bank transactions)
  - Amazon Selling Partner API (business orders)
  - Gmail API (receipt parsing)
  - LLM APIs (transaction enrichment)

  ## Critical References
  **ALWAYS consult these before database work:**
  - Database schema: `.claude/docs/database/DATABASE_SCHEMA.md` (AUTHORITATIVE)
  - Schema enforcement: `.claude/docs/database/SCHEMA_ENFORCEMENT.md`
  - Architecture: `.claude/docs/architecture/TRUELAYER_INTEGRATION.md`

  ## Tech Stack
  - Python 3.12+ with Flask 3.0.0
  - PostgreSQL 16 (Docker, port 5433)
  - Redis 7 (Docker, port 6380)
  - Celery 5.5.3 (background tasks)
  - SQLAlchemy ORM (ongoing migration from raw SQL)

  ## Key Architecture Patterns
  1. **Database**: PostgreSQL is the primary DB (NOT SQLite)
  2. **Async Tasks**: Gmail sync, enrichment run in Celery workers
  3. **File Organization**: Keep files 200-500 lines (see CLAUDE.md for rationale)
  4. **Code Quality**: Ruff + Black (no unused imports/variables)
  5. **Semantic Operations**: Use symbolic tools for code manipulation where possible

  ## Common Pitfalls
  - PostgreSQL uses non-standard port 5433 (NOT 5432)
  - Celery code changes require rebuild: `docker-compose build celery`
  - Gmail sync output appears in Celery logs, not Flask terminal
  - Always check `.env` for actual passwords (don't assume defaults)
  - Use `python3` NOT `python` in shell commands

project_name: "backend"
included_optional_tools: []
